### ISSUE TITLE
allow and add head-requests

### ISSUE THREAD

**Issue by KillerCodeMonkey** [ePages-de/epages-rest-php#114]
consider to extend util/restclient to handle head-requests.

Like "checking if an object exists" --> not returning the object itself.

Like: HEAD /products/[id] --> HTTP-Status 200 if it exists, 404 --> If not

**Comment by panvid** [comment]
How to solve it:
Create util ErrorReportingTrait with
- public error() - Returns if there is an error
- public errorMesage()
- public errorNo()
- private errorReset()
- private errorSet(int number)
- private HashMap<int, String> $ERRORMESSAGES
- private int $ERROR
