### ISSUE TITLE
OrdersFilter: setcreatedAfterDate problem

### ISSUE THREAD

**Issue by jdmseixas** [ePages-de/epages-rest-php#165]
$orderFilter->setCreatedAfterDate is not working.
$parameter is not including this property on the RESTCall.

**Comment by panvid** [comment]
Now following functions work:
- $orderFilter->setCreatedAfterDate(...)
- $orderFilter->setCreatedBeforeDate(...)
- $orderFilter->setUpdatedFromDate(...)
